name: stereo_matching
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python >=3.6
  - cudatoolkit
  - cudnn
  - pytorch=
  - torchvision
  - pip
  - pip:
      - opencv-python
      - rospkg
      - catkin_pkg
      - empy
      - numpy
